### ISSUE TITLE
5.0.0.3 HWiNFO64 not runing???

### ISSUE THREAD

**Issue by 9301039** [Minerx117/NemosMiner#98]
How to fix the following problem? Как исправить следующую проблему?
![изображение](https://github.com/Minerx117/NemosMiner/assets/13090153/02784f1f-6476-4e63-8377-bb4dbc10f807)

**Comment by UselessGuru** [comment]
Have you read https://github.com/Minerx117/NemosMiner/blob/master/ConfigHWinfo64.pdf?

You can also disable power cost calculation entirely (Untick 'Calculate power cost'). Then you don't need HWiNFO.

HWiNFO is needed because not all miners report power usage in their API so there is no way for NemosMiner to figure out the power consumption.
